[package]
authors = ["Moritz Ulrich <moritz@tarn-vedra.de>"]
name = "ratomic"
version = "0.1.0"

[dependencies]
edn = "0.3.0"
lazy_static = "1.0.0"
log = "*"
rusqlite = "0.12.0"

[dev-dependencies]
rand = "0.3"
